import { ElementRef, EventEmitter, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
import { ViewportScroller } from '@angular/common';
import { PbdsDatavizService } from './dataviz.service';
import { PbdsDatavizScatterplot } from './dataviz.interfaces';
import * as i0 from "@angular/core";
export declare class PbdsDatavizScatterplotComponent implements OnInit, OnDestroy, OnChanges {
    private _dataviz;
    private _element;
    private _scroll;
    chartClass: boolean;
    scatterplotClass: boolean;
    data: PbdsDatavizScatterplot[];
    width: number;
    height: number;
    jitterX: number;
    jitterY: number;
    xAxisType: 'date' | 'number' | 'string';
    xAxisFormatString: string;
    xAxisTicks: number;
    yAxisFormatString: string;
    yAxisTicks: number;
    yAxisMinBuffer: number;
    yAxisMaxBuffer: number;
    hideXGrid: boolean;
    hideYGrid: boolean;
    hideLegend: boolean;
    legendWidth: number;
    legendPosition: 'right' | 'bottom';
    legendLabelFormatType: 'number' | 'time';
    tooltipXLabel: string;
    tooltipXValueFormatType: 'number' | 'time';
    tooltipXValueFormatString: string;
    tooltipYLabel: string;
    tooltipYValueFormatType: 'number' | 'time';
    tooltipYValueFormatString: string;
    tooltipValueLabel: string;
    tooltipValueFormatType: 'number' | 'time';
    tooltipValueFormatString: string;
    marginTop: number;
    marginRight: number;
    marginBottom: number;
    marginLeft: number;
    theme: any;
    customColor: boolean;
    colorsArray: any[];
    hovered: EventEmitter<object>;
    clicked: EventEmitter<object>;
    tooltipHovered: EventEmitter<object>;
    tooltipClicked: EventEmitter<object>;
    private chart;
    private svg;
    private margin;
    private colorRange;
    private xAxisScale;
    private xAxisCall;
    private xAxis;
    private xAxisFormat;
    private yAxisScale;
    private yAxisCall;
    private yAxis;
    private yAxisFormat;
    private xGrid;
    private xGridCall;
    private yGrid;
    private yGridCall;
    private valueScale;
    private xAxisTickSize;
    private xAxisTickSizeOuter;
    private yAxisTickSize;
    private yAxisTickSizeOuter;
    private hideXAxis;
    private hideYAxis;
    private hideXAxisDomain;
    private hideYAxisDomain;
    private hideXAxisZero;
    private hideYAxisZero;
    private hideXAxisTicks;
    private hideYAxisTicks;
    private legendLabelFormat;
    private tooltip;
    private hideTooltip;
    private tooltipXValueFormat;
    private tooltipYValueFormat;
    private tooltipValueFormat;
    constructor(_dataviz: PbdsDatavizService, _element: ElementRef, _scroll: ViewportScroller);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    updateChart: () => void;
    legendMouseOver: (event: any, data: any) => void;
    legendMouseOut: () => void;
    legendMouseClick: (event: any, data: any) => void;
    private tooltipShow;
    private tooltipHide;
    private xAxisFormatter;
    private yAxisFormatter;
    private tooltipXValueFormatter;
    private tooltipYValueFormatter;
    private tooltipValueFormatter;
    private jitter;
    static ɵfac: i0.ɵɵFactoryDeclaration<PbdsDatavizScatterplotComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PbdsDatavizScatterplotComponent, "pbds-dataviz-scatterplot", never, { "data": { "alias": "data"; "required": false; }; "width": { "alias": "width"; "required": false; }; "height": { "alias": "height"; "required": false; }; "jitterX": { "alias": "jitterX"; "required": false; }; "jitterY": { "alias": "jitterY"; "required": false; }; "xAxisType": { "alias": "xAxisType"; "required": false; }; "xAxisFormatString": { "alias": "xAxisFormatString"; "required": false; }; "xAxisTicks": { "alias": "xAxisTicks"; "required": false; }; "yAxisFormatString": { "alias": "yAxisFormatString"; "required": false; }; "yAxisTicks": { "alias": "yAxisTicks"; "required": false; }; "yAxisMinBuffer": { "alias": "yAxisMinBuffer"; "required": false; }; "yAxisMaxBuffer": { "alias": "yAxisMaxBuffer"; "required": false; }; "hideXGrid": { "alias": "hideXGrid"; "required": false; }; "hideYGrid": { "alias": "hideYGrid"; "required": false; }; "hideLegend": { "alias": "hideLegend"; "required": false; }; "legendWidth": { "alias": "legendWidth"; "required": false; }; "legendPosition": { "alias": "legendPosition"; "required": false; }; "legendLabelFormatType": { "alias": "legendLabelFormatType"; "required": false; }; "tooltipXLabel": { "alias": "tooltipXLabel"; "required": false; }; "tooltipXValueFormatType": { "alias": "tooltipXValueFormatType"; "required": false; }; "tooltipXValueFormatString": { "alias": "tooltipXValueFormatString"; "required": false; }; "tooltipYLabel": { "alias": "tooltipYLabel"; "required": false; }; "tooltipYValueFormatType": { "alias": "tooltipYValueFormatType"; "required": false; }; "tooltipYValueFormatString": { "alias": "tooltipYValueFormatString"; "required": false; }; "tooltipValueLabel": { "alias": "tooltipValueLabel"; "required": false; }; "tooltipValueFormatType": { "alias": "tooltipValueFormatType"; "required": false; }; "tooltipValueFormatString": { "alias": "tooltipValueFormatString"; "required": false; }; "marginTop": { "alias": "marginTop"; "required": false; }; "marginRight": { "alias": "marginRight"; "required": false; }; "marginBottom": { "alias": "marginBottom"; "required": false; }; "marginLeft": { "alias": "marginLeft"; "required": false; }; "theme": { "alias": "theme"; "required": false; }; "customColor": { "alias": "customColor"; "required": false; }; "colorsArray": { "alias": "colorsArray"; "required": false; }; }, { "hovered": "hovered"; "clicked": "clicked"; "tooltipHovered": "tooltipHovered"; "tooltipClicked": "tooltipClicked"; }, never, never, false, never>;
}
