import { OnInit, OnChanges, EventEmitter, ElementRef, OnDestroy, SimpleChanges } from '@angular/core';
import { ViewportScroller, Location } from '@angular/common';
import { PbdsDatavizService } from './dataviz.service';
import { PbdsDatavizBarGrouped } from './dataviz.interfaces';
import * as i0 from "@angular/core";
export declare class PbdsDatavizBarGroupedComponent implements OnInit, OnDestroy, OnChanges {
    private _dataviz;
    private _element;
    private _scroll;
    private _location;
    chartClass: boolean;
    groupedBarClass: boolean;
    data: Array<PbdsDatavizBarGrouped>;
    width: number;
    height: number;
    vertical: boolean;
    hideXAxis: boolean;
    xAxisMaxBuffer: number;
    xAxisFormatType: 'number' | 'time';
    xAxisFormatString: string;
    xAxisTicks: number;
    xAxisTitle: string | null;
    hideYAxis: boolean;
    yAxisMaxBuffer: number;
    yAxisFormatType: 'number' | 'time';
    yAxisFormatString: string;
    yAxisTicks: number;
    marginTop: number;
    marginRight: number;
    marginBottom: number;
    marginLeft: number;
    hideLegend: boolean;
    legendWidth: number;
    legendPosition: 'right' | 'bottom';
    legendLabelFormatType: 'number' | 'time';
    legendLabelFormatString: string;
    hideTooltip: boolean;
    tooltipLabelFormatType: 'number' | 'time';
    tooltipLabelFormatString: string;
    tooltipValueFormatType: 'number';
    tooltipValueFormatString: string;
    showGrid: boolean;
    theme: 'classic' | 'sunset' | 'ocean' | 'twilight';
    gradient: boolean;
    hovered: EventEmitter<object>;
    clicked: EventEmitter<object>;
    private barScale;
    private chart;
    private svg;
    private margin;
    private colorRange;
    private xAxisMax;
    private xAxisScale;
    private xAxisCall;
    private xAxis;
    private xAxisTickSize;
    private xAxisTickSizeOuter;
    private xAxisFormat;
    private xAxisTitleMargin;
    private hideXAxisDomain;
    private hideXAxisZero;
    private hideXAxisTicks;
    private xGrid;
    private xGridCall;
    private yAxisMax;
    private yAxisScale;
    private yAxisCall;
    private yAxis;
    private yAxisFormat;
    private yAxisTickSize;
    private yAxisTickSizeOuter;
    private hideYAxisZero;
    private hideYAxisDomain;
    private hideYAxisTicks;
    private yGrid;
    private yGridCall;
    private legendLabelFormat;
    private hideGrayBars;
    private tooltip;
    private tooltipValueFormat;
    private tooltipLabelFormat;
    constructor(_dataviz: PbdsDatavizService, _element: ElementRef, _scroll: ViewportScroller, _location: Location);
    ngOnInit(): void;
    ngOnDestroy(): void;
    ngOnChanges(changes: SimpleChanges): void;
    updateChartVertical(): void;
    updateChartHorizontal(): void;
    updateLegend(): void;
    barMouseOver: (event: any, data: PbdsDatavizBarGrouped[]) => void;
    barMouseOut: () => void;
    barMouseClick: (event: any, data: any) => void;
    legendMouseOver: (event: any, data: any) => void;
    legendMouseOut: () => void;
    legendMouseClick: (event: any, data: any) => void;
    private tooltipShow;
    private tooltipHide;
    private xAxisFormatter;
    private yAxisFormatter;
    private barFill;
    static ɵfac: i0.ɵɵFactoryDeclaration<PbdsDatavizBarGroupedComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PbdsDatavizBarGroupedComponent, "pbds-dataviz-bar-grouped", never, { "data": { "alias": "data"; "required": false; }; "width": { "alias": "width"; "required": false; }; "height": { "alias": "height"; "required": false; }; "vertical": { "alias": "vertical"; "required": false; }; "hideXAxis": { "alias": "hideXAxis"; "required": false; }; "xAxisMaxBuffer": { "alias": "xAxisMaxBuffer"; "required": false; }; "xAxisFormatType": { "alias": "xAxisFormatType"; "required": false; }; "xAxisFormatString": { "alias": "xAxisFormatString"; "required": false; }; "xAxisTicks": { "alias": "xAxisTicks"; "required": false; }; "xAxisTitle": { "alias": "xAxisTitle"; "required": false; }; "hideYAxis": { "alias": "hideYAxis"; "required": false; }; "yAxisMaxBuffer": { "alias": "yAxisMaxBuffer"; "required": false; }; "yAxisFormatType": { "alias": "yAxisFormatType"; "required": false; }; "yAxisFormatString": { "alias": "yAxisFormatString"; "required": false; }; "yAxisTicks": { "alias": "yAxisTicks"; "required": false; }; "marginTop": { "alias": "marginTop"; "required": false; }; "marginRight": { "alias": "marginRight"; "required": false; }; "marginBottom": { "alias": "marginBottom"; "required": false; }; "marginLeft": { "alias": "marginLeft"; "required": false; }; "hideLegend": { "alias": "hideLegend"; "required": false; }; "legendWidth": { "alias": "legendWidth"; "required": false; }; "legendPosition": { "alias": "legendPosition"; "required": false; }; "legendLabelFormatType": { "alias": "legendLabelFormatType"; "required": false; }; "legendLabelFormatString": { "alias": "legendLabelFormatString"; "required": false; }; "hideTooltip": { "alias": "hideTooltip"; "required": false; }; "tooltipLabelFormatType": { "alias": "tooltipLabelFormatType"; "required": false; }; "tooltipLabelFormatString": { "alias": "tooltipLabelFormatString"; "required": false; }; "tooltipValueFormatType": { "alias": "tooltipValueFormatType"; "required": false; }; "tooltipValueFormatString": { "alias": "tooltipValueFormatString"; "required": false; }; "showGrid": { "alias": "showGrid"; "required": false; }; "theme": { "alias": "theme"; "required": false; }; "gradient": { "alias": "gradient"; "required": false; }; }, { "hovered": "hovered"; "clicked": "clicked"; }, never, never, false, never>;
}
