import { OnInit, ElementRef, OnChanges, SimpleChanges, EventEmitter, OnDestroy } from '@angular/core';
import { PbdsDatavizService } from './dataviz.service';
import { PbdsDatavizPie } from './dataviz.interfaces';
import * as i0 from "@angular/core";
export declare class PbdsDatavizPieComponent implements OnInit, OnChanges, OnDestroy {
    private _dataviz;
    private _element;
    chartClass: boolean;
    pieClass: boolean;
    data: Array<PbdsDatavizPie>;
    width: number;
    type: 'pie' | 'donut';
    monochrome: boolean;
    legendLabelFormatType: 'time';
    legendLabelFormatString: string;
    legendValueFormatString: string;
    tooltipLabelFormatType: 'time';
    tooltipLabelFormatString: string;
    tooltipLabelSuffix: string;
    tooltipValueFormatString: string;
    theme: any;
    customColor: boolean;
    colorsArray: any[];
    hovered: EventEmitter<any>;
    clicked: EventEmitter<any>;
    private currentData;
    private height;
    private chart;
    private margin;
    private colors;
    private colorRange;
    private arc;
    private arcZoom;
    private svg;
    private pie;
    private legendLabelFormat;
    private legendValueFormat;
    private innerRadius;
    private anglePad;
    private outerRadius;
    private tooltip;
    private tooltipLabelFormat;
    private tooltipValueFormat;
    constructor(_dataviz: PbdsDatavizService, _element: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    updateChart: (firstRun?: boolean) => void;
    private arcEnterTween;
    private arcUpdateTween;
    private arcMouseOverTween;
    private arcMouseOutTween;
    private legendMouseOverFocus;
    private legendMouseOutBlur;
    private pathMouseOver;
    private pathMouseOut;
    private pathClick;
    private tooltipShow;
    private tooltipMove;
    private tooltipHide;
    private tooltipSetPosition;
    static ɵfac: i0.ɵɵFactoryDeclaration<PbdsDatavizPieComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PbdsDatavizPieComponent, "pbds-dataviz-pie", never, { "data": { "alias": "data"; "required": false; }; "width": { "alias": "width"; "required": false; }; "type": { "alias": "type"; "required": false; }; "monochrome": { "alias": "monochrome"; "required": false; }; "legendLabelFormatType": { "alias": "legendLabelFormatType"; "required": false; }; "legendLabelFormatString": { "alias": "legendLabelFormatString"; "required": false; }; "legendValueFormatString": { "alias": "legendValueFormatString"; "required": false; }; "tooltipLabelFormatType": { "alias": "tooltipLabelFormatType"; "required": false; }; "tooltipLabelFormatString": { "alias": "tooltipLabelFormatString"; "required": false; }; "tooltipLabelSuffix": { "alias": "tooltipLabelSuffix"; "required": false; }; "tooltipValueFormatString": { "alias": "tooltipValueFormatString"; "required": false; }; "theme": { "alias": "theme"; "required": false; }; "customColor": { "alias": "customColor"; "required": false; }; "colorsArray": { "alias": "colorsArray"; "required": false; }; }, { "hovered": "hovered"; "clicked": "clicked"; }, never, never, false, never>;
}
