import { OnInit, ElementRef, OnChanges, SimpleChanges, EventEmitter, OnDestroy } from '@angular/core';
import { PbdsDatavizService } from './dataviz.service';
import { PbdsDatavizPie } from './dataviz.interfaces';
export declare class PbdsDatavizPieComponent implements OnInit, OnChanges, OnDestroy {
    private _dataviz;
    private _element;
    chartClass: boolean;
    pieClass: boolean;
    data: Array<PbdsDatavizPie>;
    width: number;
    type: 'pie' | 'donut';
    monochrome: boolean;
    legendLabelFormatType: 'time';
    legendLabelFormatString: string;
    legendValueFormatString: string;
    tooltipLabelFormatType: 'time';
    tooltipLabelFormatString: string;
    tooltipValueFormatString: string;
    theme: any;
    hovered: EventEmitter<object>;
    clicked: EventEmitter<object>;
    private currentData;
    private height;
    private chart;
    private margin;
    private colors;
    private colorRange;
    private arc;
    private arcZoom;
    private svg;
    private pie;
    private legendLabelFormat;
    private legendValueFormat;
    private innerRadius;
    private anglePad;
    private outerRadius;
    private tooltip;
    private tooltipLabelFormat;
    private tooltipValueFormat;
    constructor(_dataviz: PbdsDatavizService, _element: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    updateChart: (firstRun?: boolean) => void;
    private arcEnterTween;
    private arcTween;
    private arcExitTween;
    private arcMouseOverTween;
    private arcMouseOutTween;
    private legendMouseOverFocus;
    private legendMouseOutBlur;
    private pathMouseOver;
    private pathMouseOut;
    private pathClick;
    private tooltipShow;
    private tooltipMove;
    private tooltipHide;
    private tooltipSetPosition;
}
