import { OnInit, ElementRef, OnChanges, SimpleChanges } from '@angular/core';
import { PbdsDatavizService } from './dataviz.service';
import { PbdsDatavizGauge } from './dataviz.interfaces';
import * as i0 from "@angular/core";
export declare class PbdsDatavizGaugeComponent implements OnInit, OnChanges {
    private _dataviz;
    private _element;
    chartClass: boolean;
    gaugeClass: boolean;
    data: PbdsDatavizGauge;
    width: number;
    type: 'halfmoon' | 'horseshoe' | 'circle';
    color: string;
    hideLabel: boolean;
    labelFormatString: string;
    description: any;
    gaugeWidth: number;
    label: any;
    private chart;
    private svg;
    private gauge;
    private labelTween;
    private startAngle;
    private endAngle;
    private radius;
    private arc;
    private labelFormat;
    private oldValue;
    private height;
    private rounded;
    private detailsPaddingTop;
    constructor(_dataviz: PbdsDatavizService, _element: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    degreesToRadians: (degree: any) => number;
    calculateMinMax: () => number;
    calculateCurve: (data: any) => {
        startAngle: number;
        endAngle: number;
    }[];
    drawChart: () => void;
    updateChart: () => void;
    arcTween: (transition: any, value: any) => void;
    textTween: (transition: any, value: any) => void;
    static ɵfac: i0.ɵɵFactoryDeclaration<PbdsDatavizGaugeComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PbdsDatavizGaugeComponent, "pbds-dataviz-gauge", never, { "data": "data"; "width": "width"; "type": "type"; "color": "color"; "hideLabel": "hideLabel"; "labelFormatString": "labelFormatString"; "description": "description"; "gaugeWidth": "gaugeWidth"; }, {}, never, never, false, never>;
}
