import { ElementRef, EventEmitter, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
import { Location, ViewportScroller } from '@angular/common';
import { PbdsDatavizLine } from './dataviz.interfaces';
import { PbdsDatavizService } from './dataviz.service';
import * as i0 from "@angular/core";
export declare class PbdsDatavizLineComponent implements OnInit, OnDestroy, OnChanges {
    private _dataviz;
    private _element;
    private _scroll;
    private _location;
    chartClass: boolean;
    lineClass: boolean;
    data: PbdsDatavizLine;
    width: number;
    height: number;
    type: 'medium' | 'high' | 'debug';
    area: boolean;
    xAxisType: 'date' | 'number' | 'string';
    xAxisFormatString: string;
    xAxisTicks: number;
    xAxisTitle: string | null;
    yAxisFormatString: string;
    yAxisTicks: number;
    yAxisMinBuffer: number;
    yAxisMaxBuffer: number;
    hideXGrid: boolean;
    hideYGrid: boolean;
    hideLegend: boolean;
    legendWidth: number;
    legendPosition: 'right' | 'bottom';
    legendLabelFormatType: 'number' | 'time';
    legendLabelFormatString: string;
    tooltipHeadingFormatString: string;
    tooltipHeadingSuffix: string;
    tooltipLabelFormatType: 'number' | 'time';
    tooltipLabelFormatString: string;
    tooltipValueFormatType: 'number' | 'time';
    tooltipValueFormatString: string;
    marginTop: number;
    marginRight: number;
    marginBottom: number;
    marginLeft: number;
    theme: any;
    customColor: boolean;
    colorsArray: any[];
    lineCurved: boolean;
    hovered: EventEmitter<object>;
    clicked: EventEmitter<object>;
    tooltipHovered: EventEmitter<object>;
    tooltipClicked: EventEmitter<object>;
    private chart;
    private svg;
    private mouserect;
    private tooltipLine;
    private margin;
    private clipPathId;
    private d3line;
    private d3area;
    private lineWidth;
    private linePoints;
    private colorRange;
    private xAxisScale;
    private xAxisCall;
    private xAxis;
    private xAxisFormat;
    private yAxisScale;
    private yAxisCall;
    private yAxis;
    private yAxisFormat;
    private xGrid;
    private xGridCall;
    private yGrid;
    private yGridCall;
    private xAxisTickSize;
    private xAxisTickSizeOuter;
    private xAxisTitleMargin;
    private yAxisTickSize;
    private yAxisTickSizeOuter;
    private hideXAxis;
    private hideYAxis;
    private hideXAxisDomain;
    private hideYAxisDomain;
    private hideXAxisZero;
    private hideYAxisZero;
    private hideXAxisTicks;
    private hideYAxisTicks;
    private legendLabelFormat;
    private tooltip;
    private hideTooltip;
    private tooltipHeadingFormat;
    private tooltipValueFormat;
    private tooltipLabelFormat;
    private mousedata;
    constructor(_dataviz: PbdsDatavizService, _element: ElementRef, _scroll: ViewportScroller, _location: Location);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    updateChart: () => void;
    legendMouseOver: (event: any, data: any) => void;
    legendMouseOut: () => void;
    legendMouseClick: (event: any, data: any) => void;
    mouserectMouseMove: (event: any, data: any) => boolean;
    mouserectMouseOut: (event: any, data: any) => void;
    mouserectMouseClick: (event: any) => void;
    private tooltipShow;
    private tooltipHide;
    private xAxisFormatter;
    private yAxisFormatter;
    static ɵfac: i0.ɵɵFactoryDeclaration<PbdsDatavizLineComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PbdsDatavizLineComponent, "pbds-dataviz-line", never, { "data": { "alias": "data"; "required": false; }; "width": { "alias": "width"; "required": false; }; "height": { "alias": "height"; "required": false; }; "type": { "alias": "type"; "required": false; }; "area": { "alias": "area"; "required": false; }; "xAxisType": { "alias": "xAxisType"; "required": false; }; "xAxisFormatString": { "alias": "xAxisFormatString"; "required": false; }; "xAxisTicks": { "alias": "xAxisTicks"; "required": false; }; "xAxisTitle": { "alias": "xAxisTitle"; "required": false; }; "yAxisFormatString": { "alias": "yAxisFormatString"; "required": false; }; "yAxisTicks": { "alias": "yAxisTicks"; "required": false; }; "yAxisMinBuffer": { "alias": "yAxisMinBuffer"; "required": false; }; "yAxisMaxBuffer": { "alias": "yAxisMaxBuffer"; "required": false; }; "hideXGrid": { "alias": "hideXGrid"; "required": false; }; "hideYGrid": { "alias": "hideYGrid"; "required": false; }; "hideLegend": { "alias": "hideLegend"; "required": false; }; "legendWidth": { "alias": "legendWidth"; "required": false; }; "legendPosition": { "alias": "legendPosition"; "required": false; }; "legendLabelFormatType": { "alias": "legendLabelFormatType"; "required": false; }; "legendLabelFormatString": { "alias": "legendLabelFormatString"; "required": false; }; "tooltipHeadingFormatString": { "alias": "tooltipHeadingFormatString"; "required": false; }; "tooltipHeadingSuffix": { "alias": "tooltipHeadingSuffix"; "required": false; }; "tooltipLabelFormatType": { "alias": "tooltipLabelFormatType"; "required": false; }; "tooltipLabelFormatString": { "alias": "tooltipLabelFormatString"; "required": false; }; "tooltipValueFormatType": { "alias": "tooltipValueFormatType"; "required": false; }; "tooltipValueFormatString": { "alias": "tooltipValueFormatString"; "required": false; }; "marginTop": { "alias": "marginTop"; "required": false; }; "marginRight": { "alias": "marginRight"; "required": false; }; "marginBottom": { "alias": "marginBottom"; "required": false; }; "marginLeft": { "alias": "marginLeft"; "required": false; }; "theme": { "alias": "theme"; "required": false; }; "customColor": { "alias": "customColor"; "required": false; }; "colorsArray": { "alias": "colorsArray"; "required": false; }; "lineCurved": { "alias": "lineCurved"; "required": false; }; }, { "hovered": "hovered"; "clicked": "clicked"; "tooltipHovered": "tooltipHovered"; "tooltipClicked": "tooltipClicked"; }, never, never, false, never>;
}
